### ISSUE TITLE
THE GUI DONT WORK AT ALL

### ISSUE THREAD

**Issue by Spideyboyjk** [swagging-post/Blooket-Cheat-GUI#15]
I type in javascript: then I paste the code in and NOTHING HAPPENS

**Comment by swagging-post** [comment]
## The code already includes a Javascript: (for min.js, console will not have one)

If you're copying the **min.js** code, it **already** includes a **Javascript:** , so just paste it in without adding another one, if you're using **mobile.min.js** though, it will not work since it's usually not used as much.

**Comment by Githubman6996** [comment]
Swagging post this repo is bullshit your just skidding code and deleting anyone who says it’s a skid in an issue

**Comment by Githubman6996** [comment]
@swagging-post
